#!/bin/sh

root=$PWD;
PATH="$PWD:$PATH"

echo "----------------- $@ -----------------------"
repos=`find sources -mindepth 1 -maxdepth 1 -type d  ! -path '*.*'`

for repo in $repos; do echo; echo $repo:; cd "$root/$repo" && eval "$@"; done; cd $root
echo
